# fly.toml app configuration file generated for portfolio-v2-red-waterfall-3678 on 2025-11-20T13:16:29+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-v2-red-waterfall-3678'
primary_region = 'bom'

[build]
  dockerfile = "Dockerfile"

[env]
  TERMINAL_SSH_PORT = "22"
  TERMINAL_SSH_HOST_KEY = "/app/keys/terminal_host_ed25519"
  TERMINAL_HTTP_PORT = "8080"
  TERMINAL_HTTP_HOST = "0.0.0.0"

[[mounts]]
  source = "keys_volume"
  destination = "/app/keys"

[[services]]
  internal_port = 22
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 22
    handlers = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
